index:
	[ -f ./index.hml ] && /bin/rm -rf ./index* || true
	wget https://www.pbs.org/newshour/
player:
	wget https://player.pbs.org/widget/partnerplayer/3082974792/?chapterbar=false&endscreen=false&topbar=fal
se&autoplay=false

redir:
	wget https://urs.pbs.org/redirect/1cc4deabea3e4e1d926397fb1203c62c/
